version: "3"

networks:
  docker_nodejs_bootstrap:
    driver: bridge

services:
  api:
    container_name: docker_nodejs_bootstrap_api
    image: node
    ports:
      - "19100:3000"
    volumes:
      - ./api:/app
    working_dir: /app
    env_file:
      - .env
    # command: bash -c 'npm i && npm start' #for npm modules installation inside container without hot reloading in dev environment
    command: bash -c 'npm i && npm run dev' #for npm modules installation inside container and hot reloading in dev environment (works only if nodemon is already installed in container)
    #command: npm start #for production environment
    #restart: unless-stopped #to activate in production environment
    networks:
      - docker_nodejs_bootstrap
    depends_on:
      - db
      
  db:
    image: mariadb:latest
    container_name: docker_mariadb_bootstrap_api
    ports:
      - 3306:3306
    env_file:
      - .env
    networks:
      - docker_nodejs_bootstrap
    volumes:
      - ./data/api:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - docker_nodejs_bootstrap

  service_Users:
    container_name: docker_service_Users
    image: node
    ports:
      - "19102:3000"
    volumes:
      - ./service_Users:/app
    working_dir: /app
    env_file:
      - ./usr.env
    # command: bash -c 'npm i && npm start' #for npm modules installation inside container without hot reloading in dev environment
    command: bash -c 'npm i && npm run dev' #for npm modules installation inside container and hot reloading in dev environment (works only if nodemon is already installed in container)
    #command: npm start #for production environment
    #restart: unless-stopped #to activate in production environment
    networks:
      - docker_nodejs_bootstrap
    depends_on:
      - dbUser

  service_admin:
    container_name: docker_service_admin
    image: node
    ports:
      - "19104:3000"
    volumes:
      - ./service_admin:/app
    working_dir: /app
    env_file:
      - ./.env
    # command: bash -c 'npm i && npm start' #for npm modules installation inside container without hot reloading in dev environment
    command: bash -c 'npm i && npm run dev' #for npm modules installation inside container and hot reloading in dev environment (works only if nodemon is already installed in container)
    #command: npm start #for production environment
    #restart: unless-stopped #to activate in production environment
    networks:
      - docker_nodejs_bootstrap
    depends_on:
      - dbUser
      
  dbUser:
    image: mariadb:latest
    container_name: docker-service_Users-mariadb
    ports:
      - 3308:3306
    env_file:
      - ./usr.env
    networks:
      - docker_nodejs_bootstrap
    volumes:
      - ./data/usr:/var/lib/mysql
